name: ShiftKits
version: 1.10.4-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.shiftkits.ShiftKits
description: Part of the Shift minigame. Implements purchasable kit.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
depend: [ShiftSpawn, ShiftStats, XCore]